### ISSUE TITLE
Brain example : problem to use the constructor PNetwork

### ISSUE THREAD

**Issue by bvking** [nickmcintyre/processing-synchronization#4]
Hello Nick,
i have copy paste your brain exemple in Processing and add the constructor PNetwork.java in a new tab in Processing (as I did with your other example).
But I read this in the monitor
The constructor PNetwork(brainexemple, float[], float[], float[][]) is undefined.
What have I done wrong?
Happy to see that you keep on developing other application with the kuramato model ;)

**Comment by nickmcintyre** [comment]
Hey @bvking! Thanks for the heads up.

Have you downloaded and installed the [most recent release](https://github.com/nickmcintyre/processing-synchronization/releases/tag/v0.0.7)? I changed the interface a little, so that error would probably appear with previous versions of the library.

Yep! Just started laying groundwork for more interesting applications (including Chimera states :).
